<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bishopric;

class BishopricSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bishoprics = [
            [
                'name' => 'Arquidiócesis de Madrid',
                'slug' => 'archidiocesis-madrid',
                'description' => 'Arquidiócesis de Madrid, sede metropolitana de la provincia eclesiástica de Madrid.',
                'seat_city' => 'Madrid',
                'province' => 'Madrid',
                'region' => 'Comunidad de Madrid',
                'country' => 'España',
                'latitude' => 40.4168,
                'longitude' => -3.7038,
                'current_bishop' => 'Carlos Osoro Sierra',
                'bishop_title' => 'Arzobispo de Madrid',
                'bishop_appointment_date' => '2014-08-28',
                'foundation_date' => '1885-03-07',
                'patron_saint' => 'San Isidro Labrador',
                'address' => 'Calle Bailén, 8',
                'phone' => '+34 915 42 00 00',
                'email' => 'info@archimadrid.es',
                'website' => 'https://www.archimadrid.es',
                'type' => 'archdiocese',
                'ecclesiastical_province' => 'Madrid',
                'metropolitan' => 'Carlos Osoro Sierra',
                'area_km2' => 8028,
                'population' => 6663394,
                'catholic_population' => 5330715,
                'is_active' => true,
                'is_suffragan' => false,
                'notes' => 'Sede metropolitana de la provincia eclesiástica de Madrid.',
            ],
            [
                'name' => 'Diócesis de Barcelona',
                'slug' => 'diocesis-barcelona',
                'description' => 'Diócesis de Barcelona, sufragánea de la provincia eclesiástica de Tarragona.',
                'seat_city' => 'Barcelona',
                'province' => 'Barcelona',
                'region' => 'Cataluña',
                'country' => 'España',
                'latitude' => 41.3851,
                'longitude' => 2.1734,
                'current_bishop' => 'Juan José Omella Omella',
                'bishop_title' => 'Arzobispo de Barcelona',
                'bishop_appointment_date' => '2015-11-06',
                'foundation_date' => '343-01-01',
                'patron_saint' => 'Santa Eulalia de Barcelona',
                'address' => 'Plaça de la Seu, s/n',
                'phone' => '+34 933 15 21 54',
                'email' => 'info@arqbcn.org',
                'website' => 'https://www.arqbcn.org',
                'type' => 'archdiocese',
                'ecclesiastical_province' => 'Tarragona',
                'metropolitan' => 'Joan Planellas i Barnosell',
                'area_km2' => 3400,
                'population' => 5630000,
                'catholic_population' => 4504000,
                'is_active' => true,
                'is_suffragan' => false,
                'notes' => 'Una de las diócesis más antiguas de España.',
            ],
            [
                'name' => 'Diócesis de Sevilla',
                'slug' => 'diocesis-sevilla',
                'description' => 'Diócesis de Sevilla, sede metropolitana de la provincia eclesiástica de Sevilla.',
                'seat_city' => 'Sevilla',
                'province' => 'Sevilla',
                'region' => 'Andalucía',
                'country' => 'España',
                'latitude' => 37.3891,
                'longitude' => -5.9845,
                'current_bishop' => 'José Ángel Saiz Meneses',
                'bishop_title' => 'Arzobispo de Sevilla',
                'bishop_appointment_date' => '2021-06-12',
                'foundation_date' => '300-01-01',
                'patron_saint' => 'San Fernando',
                'address' => 'Plaza Virgen de los Reyes, s/n',
                'phone' => '+34 954 22 97 00',
                'email' => 'info@archisevilla.org',
                'website' => 'https://www.archisevilla.org',
                'type' => 'archdiocese',
                'ecclesiastical_province' => 'Sevilla',
                'metropolitan' => 'José Ángel Saiz Meneses',
                'area_km2' => 14036,
                'population' => 1940000,
                'catholic_population' => 1552000,
                'is_active' => true,
                'is_suffragan' => false,
                'notes' => 'Una de las diócesis más importantes del sur de España.',
            ],
            [
                'name' => 'Diócesis de Valencia',
                'slug' => 'diocesis-valencia',
                'description' => 'Diócesis de Valencia, sede metropolitana de la provincia eclesiástica de Valencia.',
                'seat_city' => 'Valencia',
                'province' => 'Valencia',
                'region' => 'Comunidad Valenciana',
                'country' => 'España',
                'latitude' => 39.4699,
                'longitude' => -0.3763,
                'current_bishop' => 'Enrique Benavent Vidal',
                'bishop_title' => 'Arzobispo de Valencia',
                'bishop_appointment_date' => '2022-10-15',
                'foundation_date' => '527-01-01',
                'patron_saint' => 'San Vicente Mártir',
                'address' => 'Plaza de la Reina, s/n',
                'phone' => '+34 963 91 91 00',
                'email' => 'info@archivalencia.org',
                'website' => 'https://www.archivalencia.org',
                'type' => 'archdiocese',
                'ecclesiastical_province' => 'Valencia',
                'metropolitan' => 'Enrique Benavent Vidal',
                'area_km2' => 10807,
                'population' => 2500000,
                'catholic_population' => 2000000,
                'is_active' => true,
                'is_suffragan' => false,
                'notes' => 'Diócesis histórica del Levante español.',
            ],
            [
                'name' => 'Diócesis de Bilbao',
                'slug' => 'diocesis-bilbao',
                'description' => 'Diócesis de Bilbao, sufragánea de la provincia eclesiástica de Burgos.',
                'seat_city' => 'Bilbao',
                'province' => 'Vizcaya',
                'region' => 'País Vasco',
                'country' => 'España',
                'latitude' => 43.2627,
                'longitude' => -2.9253,
                'current_bishop' => 'Joseba Segura Etxezarraga',
                'bishop_title' => 'Obispo de Bilbao',
                'bishop_appointment_date' => '2020-11-21',
                'foundation_date' => '1949-11-02',
                'patron_saint' => 'Santiago Apóstol',
                'address' => 'Plaza de Santiago, 1',
                'phone' => '+34 944 15 00 00',
                'email' => 'info@diocesisbilbao.org',
                'website' => 'https://www.diocesisbilbao.org',
                'type' => 'diocese',
                'ecclesiastical_province' => 'Burgos',
                'metropolitan' => 'Mario Iceta Gavicagogeascoa',
                'area_km2' => 2217,
                'population' => 1150000,
                'catholic_population' => 920000,
                'is_active' => true,
                'is_suffragan' => true,
                'notes' => 'Diócesis moderna creada en el siglo XX.',
            ],
            [
                'name' => 'Diócesis de Santiago de Compostela',
                'slug' => 'diocesis-santiago-compostela',
                'description' => 'Diócesis de Santiago de Compostela, sede metropolitana de la provincia eclesiástica de Santiago de Compostela.',
                'seat_city' => 'Santiago de Compostela',
                'province' => 'La Coruña',
                'region' => 'Galicia',
                'country' => 'España',
                'latitude' => 42.8805,
                'longitude' => -8.5456,
                'current_bishop' => 'Julio Ibarra González',
                'bishop_title' => 'Arzobispo de Santiago de Compostela',
                'bishop_appointment_date' => '2023-03-25',
                'foundation_date' => '1075-01-01',
                'patron_saint' => 'Santiago Apóstol',
                'address' => 'Praza do Obradoiro, s/n',
                'phone' => '+34 981 58 35 00',
                'email' => 'info@archicompostela.org',
                'website' => 'https://www.archicompostela.org',
                'type' => 'archdiocese',
                'ecclesiastical_province' => 'Santiago de Compostela',
                'metropolitan' => 'Julio Ibarra González',
                'area_km2' => 8700,
                'population' => 950000,
                'catholic_population' => 760000,
                'is_active' => true,
                'is_suffragan' => false,
                'notes' => 'Centro del Camino de Santiago y peregrinación mundial.',
            ],
        ];

        foreach ($bishoprics as $bishopricData) {
            Bishopric::updateOrCreate(
                ['slug' => $bishopricData['slug']],
                $bishopricData
            );
        }
        
        $this->command->info('✅ Obispados creados/actualizados: ' . count($bishoprics));
    }
}
