<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CatholicSaint;
use App\Models\Municipality;
use Carbon\Carbon;

class CatholicSaintSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener municipios disponibles
        $municipalities = Municipality::all();
        $madrid = $municipalities->where('name', 'Madrid')->first();
        $alcala = $municipalities->where('name', 'Alcalá de Henares')->first();
        $mostoles = $municipalities->where('name', 'Móstoles')->first();
        $barcelona = $municipalities->where('name', 'Barcelona')->first();
        $girona = $municipalities->where('name', 'Girona')->first();

        // Santos principales del santoral católico
        $saints = [
            // Santos de enero
            [
                'name' => 'Santa María, Madre de Dios',
                'canonical_name' => 'Sancta Maria, Mater Dei',
                'slug' => 'santa-maria-madre-de-dios',
                'description' => 'Solemnidad de Santa María, Madre de Dios, patrona de la Iglesia universal',
                'biography' => 'María es la Madre de Jesucristo y la Madre de la Iglesia. Su maternidad divina es el fundamento de todas sus prerrogativas.',
                'birth_date' => null,
                'death_date' => null,
                'canonization_date' => null,
                'feast_date' => '2024-01-01',
                'feast_date_optional' => null,
                'category' => 'virgin',
                'feast_type' => 'solemnity',
                'liturgical_color' => 'white',
                'patron_of' => 'Madre de Dios, Iglesia Universal',
                'is_patron' => true,
                'patronages' => ['Iglesia Universal', 'Madres', 'Familia'],
                'specialties' => 'Maternidad divina, pureza, intercesión',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Universal',
                'country' => 'Universal',
                'liturgical_rank' => 'Solemnidad',
                'prayers' => 'Ave María, Magnificat',
                'hymns' => 'Salve Regina, Alma Redemptoris Mater',
                'attributes' => ['Corona de estrellas', 'Manto azul', 'Rosa mística'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 10,
                'notes' => 'Solemnidad obligatoria en toda la Iglesia'
            ],
            [
                'name' => 'San José',
                'canonical_name' => 'Sanctus Ioseph',
                'slug' => 'san-jose',
                'description' => 'Esposo de la Virgen María y padre adoptivo de Jesús',
                'biography' => 'José fue un carpintero de Nazaret, descendiente de David, que se casó con María y fue el padre adoptivo de Jesús.',
                'birth_date' => null,
                'death_date' => null,
                'canonization_date' => null,
                'feast_date' => '2024-03-19',
                'feast_date_optional' => null,
                'category' => 'lay_person',
                'feast_type' => 'solemnity',
                'liturgical_color' => 'white',
                'patron_of' => 'Padres de familia, trabajadores, Iglesia universal',
                'is_patron' => true,
                'patronages' => ['Padres de familia', 'Trabajadores', 'Iglesia Universal', 'Carpinteros'],
                'specialties' => 'Paternidad, trabajo, silencio, obediencia',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Universal',
                'country' => 'Universal',
                'liturgical_rank' => 'Solemnidad',
                'prayers' => 'Oración a San José',
                'hymns' => 'Te Deum',
                'attributes' => ['Lirio', 'Herramientas de carpintero', 'Niño Jesús'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 9,
                'notes' => 'Patrono de la Iglesia Universal desde 1870'
            ],
            [
                'name' => 'San Francisco de Asís',
                'canonical_name' => 'Sanctus Franciscus Assisiensis',
                'slug' => 'san-francisco-de-asis',
                'description' => 'Fundador de la Orden Franciscana, patrono de la ecología',
                'biography' => 'Francisco de Asís nació en 1182 en Asís, Italia. Renunció a su riqueza para vivir en pobreza y predicar el Evangelio.',
                'birth_date' => '1182-01-01',
                'death_date' => '1226-10-03',
                'canonization_date' => '1228-07-16',
                'feast_date' => '2024-10-04',
                'feast_date_optional' => null,
                'category' => 'founder',
                'feast_type' => 'feast',
                'liturgical_color' => 'white',
                'patron_of' => 'Ecología, animales, paz, pobres',
                'is_patron' => true,
                'patronages' => ['Ecología', 'Animales', 'Paz', 'Pobres', 'Franciscanos'],
                'specialties' => 'Pobreza, ecología, paz, amor a la creación',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Italia',
                'country' => 'Italia',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración de San Francisco, Cántico de las Criaturas',
                'hymns' => 'Señor, hazme instrumento de tu paz',
                'attributes' => ['Túnica marrón', 'Estigmas', 'Lobo', 'Pájaros'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 9,
                'notes' => 'Patrono de la ecología desde 1979'
            ],

            // Santos patronos de Madrid
            [
                'name' => 'San Isidro Labrador',
                'canonical_name' => 'Sanctus Isidorus Agricola',
                'slug' => 'san-isidro-labrador',
                'description' => 'Patrono de Madrid y de los agricultores',
                'biography' => 'Isidro nació en Madrid hacia 1082. Fue un labrador piadoso que realizó numerosos milagros relacionados con la agricultura.',
                'birth_date' => '1082-01-01',
                'death_date' => '1172-05-15',
                'canonization_date' => '1622-03-12',
                'feast_date' => '2024-05-15',
                'feast_date_optional' => null,
                'category' => 'lay_person',
                'feast_type' => 'feast',
                'liturgical_color' => 'white',
                'patron_of' => 'Madrid, agricultores, labradores',
                'is_patron' => true,
                'patronages' => ['Madrid', 'Agricultores', 'Labradores', 'Campesinos'],
                'specialties' => 'Agricultura, trabajo, humildad, milagros',
                'birth_place_id' => $madrid ? $madrid->id : null,
                'death_place_id' => $madrid ? $madrid->id : null,
                'municipality_id' => $madrid ? $madrid->id : null,
                'region' => 'Madrid',
                'country' => 'España',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración a San Isidro',
                'hymns' => 'Himno a San Isidro',
                'attributes' => ['Arado', 'Bueyes', 'Pozo', 'Trigo'],
                'is_active' => true,
                'is_universal' => false,
                'is_local' => true,
                'popularity_score' => 8,
                'notes' => 'Patrono principal de Madrid desde 1622'
            ],

            // Santos patronos de Alcalá de Henares
            [
                'name' => 'Santos Justo y Pastor',
                'canonical_name' => 'Sancti Iustus et Pastor',
                'slug' => 'santos-justo-y-pastor',
                'description' => 'Mártires infantiles, patronos de Alcalá de Henares',
                'biography' => 'Justo y Pastor fueron dos hermanos de 7 y 9 años que fueron martirizados en Alcalá de Henares durante la persecución de Diocleciano.',
                'birth_date' => null,
                'death_date' => '304-08-06',
                'canonization_date' => null,
                'feast_date' => '2024-08-06',
                'feast_date_optional' => null,
                'category' => 'martyr',
                'feast_type' => 'feast',
                'liturgical_color' => 'red',
                'patron_of' => 'Alcalá de Henares, niños, estudiantes',
                'is_patron' => true,
                'patronages' => ['Alcalá de Henares', 'Niños', 'Estudiantes', 'Mártires infantiles'],
                'specialties' => 'Valentía infantil, martirio, protección de niños',
                'birth_place_id' => $alcala ? $alcala->id : null,
                'death_place_id' => $alcala ? $alcala->id : null,
                'municipality_id' => $alcala ? $alcala->id : null,
                'region' => 'Madrid',
                'country' => 'España',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración a los Santos Mártires',
                'hymns' => 'Himno a los Santos Justo y Pastor',
                'attributes' => ['Palmas de mártir', 'Coronas', 'Túnica blanca'],
                'is_active' => true,
                'is_universal' => false,
                'is_local' => true,
                'popularity_score' => 7,
                'notes' => 'Patronos de Alcalá de Henares desde la Edad Media'
            ],

            // Santos patronos de Móstoles
            [
                'name' => 'Virgen de los Santos',
                'canonical_name' => 'Beata Maria Virginum',
                'slug' => 'virgen-de-los-santos',
                'description' => 'Patrona de Móstoles, advocación mariana local',
                'biography' => 'La Virgen de los Santos es una advocación mariana venerada en Móstoles desde la Edad Media.',
                'birth_date' => null,
                'death_date' => null,
                'canonization_date' => null,
                'feast_date' => '2024-09-08',
                'feast_date_optional' => null,
                'category' => 'virgin',
                'feast_type' => 'feast',
                'liturgical_color' => 'white',
                'patron_of' => 'Móstoles, protección maternal',
                'is_patron' => true,
                'patronages' => ['Móstoles', 'Protección maternal', 'Familia'],
                'specialties' => 'Protección, intercesión, maternidad espiritual',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => $mostoles ? $mostoles->id : null,
                'region' => 'Madrid',
                'country' => 'España',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Ave María, Salve',
                'hymns' => 'Himno a la Virgen de los Santos',
                'attributes' => ['Corona', 'Manto azul', 'Niño Jesús'],
                'is_active' => true,
                'is_universal' => false,
                'is_local' => true,
                'popularity_score' => 6,
                'notes' => 'Patrona de Móstoles desde la Edad Media'
            ],

            // Santos patronos de Cataluña
            [
                'name' => 'San Jorge',
                'canonical_name' => 'Sanctus Georgius',
                'slug' => 'san-jorge',
                'description' => 'Mártir y patrón de Cataluña, Inglaterra y otros países',
                'biography' => 'San Jorge fue un soldado romano que se convirtió al cristianismo y fue martirizado por su fe. Es famoso por la leyenda del dragón.',
                'birth_date' => null,
                'death_date' => '303-04-23',
                'canonization_date' => null,
                'feast_date' => '2024-04-23',
                'feast_date_optional' => null,
                'category' => 'martyr',
                'feast_type' => 'feast',
                'liturgical_color' => 'red',
                'patron_of' => 'Cataluña, Inglaterra, caballeros, scouts',
                'is_patron' => true,
                'patronages' => ['Cataluña', 'Inglaterra', 'Caballeros', 'Scouts', 'Soldados'],
                'specialties' => 'Valentía, caballería, protección, lucha contra el mal',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => $barcelona ? $barcelona->id : null,
                'region' => 'Cataluña',
                'country' => 'España',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración a San Jorge',
                'hymns' => 'Himno a San Jorge',
                'attributes' => ['Lanza', 'Escudo', 'Dragón', 'Caballo blanco'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 8,
                'notes' => 'Patrono de Cataluña desde la Edad Media'
            ],

            // Santos universales importantes
            [
                'name' => 'San Pedro',
                'canonical_name' => 'Sanctus Petrus',
                'slug' => 'san-pedro',
                'description' => 'Apóstol, primer Papa de la Iglesia Católica',
                'biography' => 'Simón Pedro fue uno de los doce apóstoles de Jesús y el primer Papa de la Iglesia Católica. Fue crucificado en Roma.',
                'birth_date' => null,
                'death_date' => '64-06-29',
                'canonization_date' => null,
                'feast_date' => '2024-06-29',
                'feast_date_optional' => null,
                'category' => 'apostle',
                'feast_type' => 'solemnity',
                'liturgical_color' => 'white',
                'patron_of' => 'Papa, Iglesia, pescadores, Roma',
                'is_patron' => true,
                'patronages' => ['Papa', 'Iglesia', 'Pescadores', 'Roma', 'Vaticano'],
                'specialties' => 'Pesca milagrosa, confesión de fe, liderazgo apostólico',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Universal',
                'country' => 'Universal',
                'liturgical_rank' => 'Solemnidad',
                'prayers' => 'Oración a San Pedro',
                'hymns' => 'Tu es Petrus',
                'attributes' => ['Llaves del cielo', 'Tiara papal', 'Cruz invertida'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 10,
                'notes' => 'Fundador de la Iglesia Católica'
            ],
            [
                'name' => 'San Pablo',
                'canonical_name' => 'Sanctus Paulus',
                'slug' => 'san-pablo',
                'description' => 'Apóstol de los gentiles, gran misionero del cristianismo',
                'biography' => 'Pablo de Tarso fue un fariseo que se convirtió al cristianismo después de una visión de Jesús. Evangelizó el mundo grecorromano.',
                'birth_date' => null,
                'death_date' => '67-06-29',
                'canonization_date' => null,
                'feast_date' => '2024-06-29',
                'feast_date_optional' => null,
                'category' => 'apostle',
                'feast_type' => 'solemnity',
                'liturgical_color' => 'white',
                'patron_of' => 'Misioneros, teólogos, escritores',
                'is_patron' => true,
                'patronages' => ['Misioneros', 'Teólogos', 'Escritores', 'Periodistas'],
                'specialties' => 'Evangelización, teología, cartas apostólicas',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Universal',
                'country' => 'Universal',
                'liturgical_rank' => 'Solemnidad',
                'prayers' => 'Oración a San Pablo',
                'hymns' => 'Himno a San Pablo',
                'attributes' => ['Espada', 'Libro', 'Barco', 'Espinas'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 9,
                'notes' => 'Autor de gran parte del Nuevo Testamento'
            ],

            // Santos españoles importantes
            [
                'name' => 'Santa Teresa de Jesús',
                'canonical_name' => 'Sancta Teresia a Iesu',
                'slug' => 'santa-teresa-de-jesus',
                'description' => 'Doctora de la Iglesia, fundadora de las Carmelitas Descalzas',
                'biography' => 'Teresa de Ávila fue una monja carmelita, mística y escritora española. Reformó la orden carmelita y escribió obras espirituales importantes.',
                'birth_date' => '1515-03-28',
                'death_date' => '1582-10-15',
                'canonization_date' => '1622-03-12',
                'feast_date' => '2024-10-15',
                'feast_date_optional' => null,
                'category' => 'doctor',
                'feast_type' => 'feast',
                'liturgical_color' => 'white',
                'patron_of' => 'España, escritores, reformadores',
                'is_patron' => true,
                'patronages' => ['España', 'Escritores', 'Reformadores', 'Místicos'],
                'specialties' => 'Mística, oración, reforma religiosa, escritura espiritual',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Castilla y León',
                'country' => 'España',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración de Santa Teresa',
                'hymns' => 'Nada te turbe',
                'attributes' => ['Pluma', 'Libro', 'Corazón traspasado', 'Rosa'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 8,
                'notes' => 'Primera mujer Doctora de la Iglesia'
            ],
            [
                'name' => 'San Ignacio de Loyola',
                'canonical_name' => 'Sanctus Ignatius de Loyola',
                'slug' => 'san-ignacio-de-loyola',
                'description' => 'Fundador de la Compañía de Jesús (Jesuitas)',
                'biography' => 'Ignacio de Loyola fue un soldado español que se convirtió y fundó la Compañía de Jesús. Es conocido por sus Ejercicios Espirituales.',
                'birth_date' => '1491-01-01',
                'death_date' => '1556-07-31',
                'canonization_date' => '1622-03-12',
                'feast_date' => '2024-07-31',
                'feast_date_optional' => null,
                'category' => 'founder',
                'feast_type' => 'feast',
                'liturgical_color' => 'white',
                'patron_of' => 'Ejercicios espirituales, retiros, soldados',
                'is_patron' => true,
                'patronages' => ['Ejercicios espirituales', 'Retiros', 'Soldados', 'Jesuitas'],
                'specialties' => 'Ejercicios espirituales, discernimiento, formación espiritual',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'País Vasco',
                'country' => 'España',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración de San Ignacio',
                'hymns' => 'Himno a San Ignacio',
                'attributes' => ['Libro de ejercicios', 'Monograma IHS', 'Corazón'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 8,
                'notes' => 'Fundador de los Jesuitas en 1540'
            ],

            // Santos del medio ambiente y sostenibilidad
            [
                'name' => 'San Juan Pablo II',
                'canonical_name' => 'Sanctus Ioannes Paulus II',
                'slug' => 'san-juan-pablo-ii',
                'description' => 'Papa polaco, promotor de la justicia social y la paz',
                'biography' => 'Karol Wojtyła fue Papa de 1978 a 2005. Promovió la justicia social, la paz mundial y el diálogo interreligioso.',
                'birth_date' => '1920-05-18',
                'death_date' => '2005-04-02',
                'canonization_date' => '2014-04-27',
                'feast_date' => '2024-10-22',
                'feast_date_optional' => null,
                'category' => 'pope',
                'feast_type' => 'feast',
                'liturgical_color' => 'white',
                'patron_of' => 'Jóvenes, familias, paz mundial',
                'is_patron' => true,
                'patronages' => ['Jóvenes', 'Familias', 'Paz mundial', 'Polonia'],
                'specialties' => 'Juventud, familia, paz, ecumenismo, viajes apostólicos',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Universal',
                'country' => 'Polonia',
                'liturgical_rank' => 'Fiesta',
                'prayers' => 'Oración a San Juan Pablo II',
                'hymns' => 'Himno a San Juan Pablo II',
                'attributes' => ['Tiara papal', 'Bastón pastoral', 'Rosa'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 9,
                'notes' => 'Papa más viajero de la historia'
            ],

            // Santos de fechas especiales
            [
                'name' => 'San Valentín',
                'canonical_name' => 'Sanctus Valentinus',
                'slug' => 'san-valentin',
                'description' => 'Mártir romano, patrón de los enamorados',
                'biography' => 'Valentín fue un sacerdote romano que casaba a los soldados en secreto, desobedeciendo las órdenes del emperador.',
                'birth_date' => null,
                'death_date' => '269-02-14',
                'canonization_date' => null,
                'feast_date' => '2024-02-14',
                'feast_date_optional' => null,
                'category' => 'martyr',
                'feast_type' => 'memorial',
                'liturgical_color' => 'red',
                'patron_of' => 'Enamorados, matrimonios, apicultores',
                'is_patron' => true,
                'patronages' => ['Enamorados', 'Matrimonios', 'Apicultores', 'Epilepsia'],
                'specialties' => 'Amor, matrimonio, protección de enamorados',
                'birth_place_id' => null,
                'death_place_id' => null,
                'municipality_id' => null,
                'region' => 'Universal',
                'country' => 'Italia',
                'liturgical_rank' => 'Memoria',
                'prayers' => 'Oración a San Valentín',
                'hymns' => 'Himno a San Valentín',
                'attributes' => ['Corazón', 'Rosa', 'Paloma'],
                'is_active' => true,
                'is_universal' => true,
                'is_local' => false,
                'popularity_score' => 7,
                'notes' => 'Patrono de los enamorados desde la Edad Media'
            ]
        ];

        // Crear los santos
        foreach ($saints as $saintData) {
            CatholicSaint::create($saintData);
        }

        $this->command->info('✅ Se han creado ' . count($saints) . ' santos en el santoral católico.');
        $this->command->info('📅 Santos universales, patronos locales y especiales incluidos.');
        $this->command->info('🏛️ Patronos de Madrid, Alcalá, Móstoles, Barcelona y Girona configurados.');
        $this->command->info('🌍 Santos de diferentes categorías y épocas agregados.');
        $this->command->info('📚 Santos doctores, apóstoles y fundadores incluidos.');
    }
}
