<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MediaContact;
use App\Models\MediaOutlet;
use Carbon\Carbon;

class MediaContactsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener medios de comunicación existentes
        $mediaOutlets = MediaOutlet::all();
        
        if ($mediaOutlets->isEmpty()) {
            $this->command->warn('No hay medios de comunicación disponibles. Ejecuta MediaOutletsSeeder primero.');
            return;
        }

        $contacts = [
            // Contactos de prensa
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'prensa',
                'contact_name' => 'María González',
                'job_title' => 'Jefa de Prensa',
                'department' => 'Comunicación',
                'phone' => '+34 91 123 4567',
                'mobile_phone' => '+34 600 123 456',
                'email' => 'maria.gonzalez@medio.com',
                'secondary_email' => 'prensa@medio.com',
                'specializations' => ['energia', 'sostenibilidad', 'medio_ambiente'],
                'coverage_areas' => ['madrid', 'nacional'],
                'preferred_contact_method' => 'email',
                'availability_schedule' => [
                    'monday' => ['start' => '09:00', 'end' => '18:00'],
                    'tuesday' => ['start' => '09:00', 'end' => '18:00'],
                    'wednesday' => ['start' => '09:00', 'end' => '18:00'],
                    'thursday' => ['start' => '09:00', 'end' => '18:00'],
                    'friday' => ['start' => '09:00', 'end' => '17:00'],
                    'saturday' => 'off',
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => true,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 5,
                'response_rate' => 0.85,
                'contacts_count' => 45,
                'successful_contacts' => 38,
                'social_media_profiles' => [
                    'twitter' => '@MariaGonzalezPress',
                    'linkedin' => 'maria-gonzalez-prensa',
                ],
                'bio' => 'Experta en comunicación de energías renovables con más de 10 años de experiencia.',
                'recent_articles' => [
                    'El futuro de la energía solar en España',
                    'Nuevas políticas de sostenibilidad',
                ],
                'notes' => 'Muy receptiva a comunicados sobre innovación energética',
                'interaction_history' => [
                    [
                        'type' => 'press_release',
                        'description' => 'Envío de comunicado sobre nueva instalación solar',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(5)->toISOString(),
                    ],
                    [
                        'type' => 'interview_request',
                        'description' => 'Solicitud de entrevista sobre políticas energéticas',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(15)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(5),
                'last_response_at' => Carbon::now()->subDays(4),
                'verified_at' => Carbon::now()->subMonths(2),
            ],

            // Editor
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'editor',
                'contact_name' => 'Carlos Rodríguez',
                'job_title' => 'Editor de Sección Energía',
                'department' => 'Redacción',
                'phone' => '+34 93 234 5678',
                'mobile_phone' => '+34 600 234 567',
                'email' => 'carlos.rodriguez@medio.com',
                'secondary_email' => null,
                'specializations' => ['energia', 'tecnologia', 'innovacion'],
                'coverage_areas' => ['barcelona', 'cataluna'],
                'preferred_contact_method' => 'mobile_phone',
                'availability_schedule' => [
                    'monday' => ['start' => '08:00', 'end' => '20:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '20:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '20:00'],
                    'thursday' => ['start' => '08:00', 'end' => '20:00'],
                    'friday' => ['start' => '08:00', 'end' => '19:00'],
                    'saturday' => ['start' => '10:00', 'end' => '16:00'],
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => false,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 4,
                'response_rate' => 0.75,
                'contacts_count' => 32,
                'successful_contacts' => 24,
                'social_media_profiles' => [
                    'twitter' => '@CarlosRodriguezEd',
                    'linkedin' => 'carlos-rodriguez-editor',
                ],
                'bio' => 'Editor especializado en energía y tecnología con enfoque en sostenibilidad.',
                'recent_articles' => [
                    'Innovaciones en energía eólica',
                    'El impacto de las nuevas tecnologías solares',
                ],
                'notes' => 'Prefiere contenido técnico y datos concretos',
                'interaction_history' => [
                    [
                        'type' => 'press_release',
                        'description' => 'Envío de comunicado técnico sobre nueva tecnología',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(8)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(8),
                'last_response_at' => Carbon::now()->subDays(7),
                'verified_at' => Carbon::now()->subMonths(1),
            ],

            // Corresponsal
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'corresponsal',
                'contact_name' => 'Ana Martínez',
                'job_title' => 'Corresponsal de Medio Ambiente',
                'department' => 'Redacción',
                'phone' => '+34 95 345 6789',
                'mobile_phone' => '+34 600 345 678',
                'email' => 'ana.martinez@medio.com',
                'secondary_email' => 'corresponsal@medio.com',
                'specializations' => ['medio_ambiente', 'cambio_climatico', 'sostenibilidad'],
                'coverage_areas' => ['sevilla', 'andalucia'],
                'preferred_contact_method' => 'mobile_phone',
                'availability_schedule' => [
                    'monday' => ['start' => '07:00', 'end' => '22:00'],
                    'tuesday' => ['start' => '07:00', 'end' => '22:00'],
                    'wednesday' => ['start' => '07:00', 'end' => '22:00'],
                    'thursday' => ['start' => '07:00', 'end' => '22:00'],
                    'friday' => ['start' => '07:00', 'end' => '22:00'],
                    'saturday' => ['start' => '09:00', 'end' => '18:00'],
                    'sunday' => ['start' => '10:00', 'end' => '16:00'],
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => true,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 5,
                'response_rate' => 0.90,
                'contacts_count' => 28,
                'successful_contacts' => 25,
                'social_media_profiles' => [
                    'twitter' => '@AnaMartinezEnv',
                    'instagram' => '@ana_martinez_env',
                ],
                'bio' => 'Corresponsal especializada en medio ambiente y cambio climático.',
                'recent_articles' => [
                    'Los efectos del cambio climático en Andalucía',
                    'Nuevas iniciativas de sostenibilidad urbana',
                ],
                'notes' => 'Muy activa en redes sociales, excelente para difusión',
                'interaction_history' => [
                    [
                        'type' => 'event_invitation',
                        'description' => 'Invitación a evento sobre sostenibilidad',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(3)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(3),
                'last_response_at' => Carbon::now()->subDays(2),
                'verified_at' => Carbon::now()->subMonths(3),
            ],

            // Freelancer
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'freelancer',
                'contact_name' => 'David López',
                'job_title' => 'Periodista Freelance',
                'department' => null,
                'phone' => '+34 98 456 7890',
                'mobile_phone' => '+34 600 456 789',
                'email' => 'david.lopez@freelance.com',
                'secondary_email' => null,
                'specializations' => ['energia', 'tecnologia', 'innovacion', 'startups'],
                'coverage_areas' => ['nacional', 'internacional'],
                'preferred_contact_method' => 'email',
                'availability_schedule' => [
                    'monday' => ['start' => '09:00', 'end' => '18:00'],
                    'tuesday' => ['start' => '09:00', 'end' => '18:00'],
                    'wednesday' => ['start' => '09:00', 'end' => '18:00'],
                    'thursday' => ['start' => '09:00', 'end' => '18:00'],
                    'friday' => ['start' => '09:00', 'end' => '17:00'],
                    'saturday' => 'off',
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => true,
                'is_freelancer' => true,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 3,
                'response_rate' => 0.70,
                'contacts_count' => 15,
                'successful_contacts' => 10,
                'social_media_profiles' => [
                    'twitter' => '@DavidLopezTech',
                    'linkedin' => 'david-lopez-freelance',
                    'medium' => '@davidlopez',
                ],
                'bio' => 'Periodista freelance especializado en tecnología y energía.',
                'recent_articles' => [
                    'Startups españolas en el sector energético',
                    'Tendencias en tecnología verde',
                ],
                'notes' => 'Trabaja para múltiples medios, buena cobertura',
                'interaction_history' => [
                    [
                        'type' => 'interview_request',
                        'description' => 'Solicitud de entrevista sobre startup energética',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(10)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(10),
                'last_response_at' => Carbon::now()->subDays(9),
                'verified_at' => Carbon::now()->subMonths(6),
            ],

            // Jefe de Redacción
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'jefe_redaccion',
                'contact_name' => 'Laura Sánchez',
                'job_title' => 'Jefa de Redacción',
                'department' => 'Redacción',
                'phone' => '+34 91 567 8901',
                'mobile_phone' => '+34 600 567 890',
                'email' => 'laura.sanchez@medio.com',
                'secondary_email' => 'redaccion@medio.com',
                'specializations' => ['energia', 'economia', 'politica'],
                'coverage_areas' => ['madrid', 'nacional'],
                'preferred_contact_method' => 'email',
                'availability_schedule' => [
                    'monday' => ['start' => '08:00', 'end' => '19:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '19:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '19:00'],
                    'thursday' => ['start' => '08:00', 'end' => '19:00'],
                    'friday' => ['start' => '08:00', 'end' => '18:00'],
                    'saturday' => 'off',
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => false,
                'accepts_events_invitations' => false,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 4,
                'response_rate' => 0.80,
                'contacts_count' => 52,
                'successful_contacts' => 42,
                'social_media_profiles' => [
                    'twitter' => '@LauraSanchezJefe',
                    'linkedin' => 'laura-sanchez-jefa-redaccion',
                ],
                'bio' => 'Jefa de redacción con amplia experiencia en periodismo económico.',
                'recent_articles' => [
                    'Análisis del mercado energético español',
                    'Políticas energéticas del gobierno',
                ],
                'notes' => 'Muy selectiva con el contenido, prefiere exclusivas',
                'interaction_history' => [
                    [
                        'type' => 'press_release',
                        'description' => 'Envío de comunicado sobre resultados financieros',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(12)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(12),
                'last_response_at' => Carbon::now()->subDays(11),
                'verified_at' => Carbon::now()->subMonths(4),
            ],

            // Director
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'director',
                'contact_name' => 'Roberto Fernández',
                'job_title' => 'Director de Comunicación',
                'department' => 'Dirección',
                'phone' => '+34 96 678 9012',
                'mobile_phone' => '+34 600 678 901',
                'email' => 'roberto.fernandez@medio.com',
                'secondary_email' => 'direccion@medio.com',
                'specializations' => ['energia', 'economia', 'politica', 'sostenibilidad'],
                'coverage_areas' => ['valencia', 'comunidad_valenciana'],
                'preferred_contact_method' => 'phone',
                'availability_schedule' => [
                    'monday' => ['start' => '09:00', 'end' => '18:00'],
                    'tuesday' => ['start' => '09:00', 'end' => '18:00'],
                    'wednesday' => ['start' => '09:00', 'end' => '18:00'],
                    'thursday' => ['start' => '09:00', 'end' => '18:00'],
                    'friday' => ['start' => '09:00', 'end' => '17:00'],
                    'saturday' => 'off',
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => true,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 5,
                'response_rate' => 0.95,
                'contacts_count' => 38,
                'successful_contacts' => 36,
                'social_media_profiles' => [
                    'twitter' => '@RobertoFernandezDir',
                    'linkedin' => 'roberto-fernandez-director',
                ],
                'bio' => 'Director de comunicación con visión estratégica en energía y sostenibilidad.',
                'recent_articles' => [
                    'Estrategias de comunicación en el sector energético',
                    'El futuro de la comunicación corporativa',
                ],
                'notes' => 'Muy receptivo, excelente para relaciones institucionales',
                'interaction_history' => [
                    [
                        'type' => 'event_invitation',
                        'description' => 'Invitación a evento corporativo',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(7)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(7),
                'last_response_at' => Carbon::now()->subDays(6),
                'verified_at' => Carbon::now()->subMonths(1),
            ],

            // Comunicación
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'comunicacion',
                'contact_name' => 'Isabel García',
                'job_title' => 'Responsable de Comunicación',
                'department' => 'Comunicación',
                'phone' => '+34 94 789 0123',
                'mobile_phone' => '+34 600 789 012',
                'email' => 'isabel.garcia@medio.com',
                'secondary_email' => 'comunicacion@medio.com',
                'specializations' => ['energia', 'sostenibilidad', 'innovacion'],
                'coverage_areas' => ['bilbao', 'pais_vasco'],
                'preferred_contact_method' => 'email',
                'availability_schedule' => [
                    'monday' => ['start' => '08:30', 'end' => '17:30'],
                    'tuesday' => ['start' => '08:30', 'end' => '17:30'],
                    'wednesday' => ['start' => '08:30', 'end' => '17:30'],
                    'thursday' => ['start' => '08:30', 'end' => '17:30'],
                    'friday' => ['start' => '08:30', 'end' => '16:30'],
                    'saturday' => 'off',
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => true,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 4,
                'response_rate' => 0.85,
                'contacts_count' => 41,
                'successful_contacts' => 35,
                'social_media_profiles' => [
                    'twitter' => '@IsabelGarciaCom',
                    'linkedin' => 'isabel-garcia-comunicacion',
                ],
                'bio' => 'Especialista en comunicación de energías renovables y sostenibilidad.',
                'recent_articles' => [
                    'Comunicación efectiva en el sector energético',
                    'Nuevas tendencias en comunicación sostenible',
                ],
                'notes' => 'Muy profesional, buena para contenido técnico',
                'interaction_history' => [
                    [
                        'type' => 'press_release',
                        'description' => 'Envío de comunicado sobre nueva tecnología',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(6)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(6),
                'last_response_at' => Carbon::now()->subDays(5),
                'verified_at' => Carbon::now()->subMonths(2),
            ],

            // Relaciones Públicas
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'relaciones_publicas',
                'contact_name' => 'Miguel Torres',
                'job_title' => 'Responsable de Relaciones Públicas',
                'department' => 'Relaciones Públicas',
                'phone' => '+34 91 890 1234',
                'mobile_phone' => '+34 600 890 123',
                'email' => 'miguel.torres@medio.com',
                'secondary_email' => 'rrpp@medio.com',
                'specializations' => ['energia', 'sostenibilidad', 'eventos'],
                'coverage_areas' => ['madrid', 'nacional'],
                'preferred_contact_method' => 'mobile_phone',
                'availability_schedule' => [
                    'monday' => ['start' => '09:00', 'end' => '19:00'],
                    'tuesday' => ['start' => '09:00', 'end' => '19:00'],
                    'wednesday' => ['start' => '09:00', 'end' => '19:00'],
                    'thursday' => ['start' => '09:00', 'end' => '19:00'],
                    'friday' => ['start' => '09:00', 'end' => '18:00'],
                    'saturday' => ['start' => '10:00', 'end' => '14:00'],
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => true,
                'accepts_events_invitations' => true,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 4,
                'response_rate' => 0.88,
                'contacts_count' => 33,
                'successful_contacts' => 29,
                'social_media_profiles' => [
                    'twitter' => '@MiguelTorresRRPP',
                    'linkedin' => 'miguel-torres-rrpp',
                ],
                'bio' => 'Experto en relaciones públicas especializado en eventos energéticos.',
                'recent_articles' => [
                    'Organización de eventos sostenibles',
                    'Relaciones públicas en el sector energético',
                ],
                'notes' => 'Excelente para eventos y networking',
                'interaction_history' => [
                    [
                        'type' => 'event_invitation',
                        'description' => 'Invitación a evento de networking energético',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(4)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(4),
                'last_response_at' => Carbon::now()->subDays(3),
                'verified_at' => Carbon::now()->subMonths(5),
            ],

            // Fotógrafo
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'fotografo',
                'contact_name' => 'Elena Ruiz',
                'job_title' => 'Fotógrafa de Prensa',
                'department' => 'Fotografía',
                'phone' => '+34 95 901 2345',
                'mobile_phone' => '+34 600 901 234',
                'email' => 'elena.ruiz@medio.com',
                'secondary_email' => 'fotografia@medio.com',
                'specializations' => ['energia', 'medio_ambiente', 'tecnologia'],
                'coverage_areas' => ['sevilla', 'andalucia'],
                'preferred_contact_method' => 'mobile_phone',
                'availability_schedule' => [
                    'monday' => ['start' => '08:00', 'end' => '20:00'],
                    'tuesday' => ['start' => '08:00', 'end' => '20:00'],
                    'wednesday' => ['start' => '08:00', 'end' => '20:00'],
                    'thursday' => ['start' => '08:00', 'end' => '20:00'],
                    'friday' => ['start' => '08:00', 'end' => '20:00'],
                    'saturday' => ['start' => '09:00', 'end' => '18:00'],
                    'sunday' => ['start' => '10:00', 'end' => '16:00'],
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => false,
                'accepts_interviews' => false,
                'accepts_events_invitations' => true,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 3,
                'response_rate' => 0.75,
                'contacts_count' => 22,
                'successful_contacts' => 16,
                'social_media_profiles' => [
                    'instagram' => '@ElenaRuizPhoto',
                    'twitter' => '@ElenaRuizPhoto',
                ],
                'bio' => 'Fotógrafa especializada en energía y medio ambiente.',
                'recent_articles' => [
                    'Galería: Instalaciones solares en Andalucía',
                    'Fotoreportaje: El futuro de la energía eólica',
                ],
                'notes' => 'Excelente calidad fotográfica, muy creativa',
                'interaction_history' => [
                    [
                        'type' => 'event_invitation',
                        'description' => 'Invitación a cobertura fotográfica de evento',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(9)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(9),
                'last_response_at' => Carbon::now()->subDays(8),
                'verified_at' => Carbon::now()->subMonths(7),
            ],

            // Técnico
            [
                'media_outlet_id' => $mediaOutlets->random()->id,
                'type' => 'tecnico',
                'contact_name' => 'Javier Moreno',
                'job_title' => 'Técnico de Comunicación',
                'department' => 'Técnico',
                'phone' => '+34 96 012 3456',
                'mobile_phone' => '+34 600 012 345',
                'email' => 'javier.moreno@medio.com',
                'secondary_email' => 'tecnico@medio.com',
                'specializations' => ['tecnologia', 'innovacion', 'digital'],
                'coverage_areas' => ['valencia', 'comunidad_valenciana'],
                'preferred_contact_method' => 'email',
                'availability_schedule' => [
                    'monday' => ['start' => '09:00', 'end' => '18:00'],
                    'tuesday' => ['start' => '09:00', 'end' => '18:00'],
                    'wednesday' => ['start' => '09:00', 'end' => '18:00'],
                    'thursday' => ['start' => '09:00', 'end' => '18:00'],
                    'friday' => ['start' => '09:00', 'end' => '17:00'],
                    'saturday' => 'off',
                    'sunday' => 'off',
                ],
                'language_preference' => 'es',
                'accepts_press_releases' => true,
                'accepts_interviews' => false,
                'accepts_events_invitations' => false,
                'is_freelancer' => false,
                'is_active' => true,
                'is_verified' => true,
                'priority_level' => 2,
                'response_rate' => 0.65,
                'contacts_count' => 18,
                'successful_contacts' => 12,
                'social_media_profiles' => [
                    'linkedin' => 'javier-moreno-tecnico',
                ],
                'bio' => 'Técnico especializado en comunicación digital y tecnología.',
                'recent_articles' => [
                    'Nuevas tecnologías en comunicación',
                    'Digitalización del sector energético',
                ],
                'notes' => 'Muy técnico, prefiere contenido especializado',
                'interaction_history' => [
                    [
                        'type' => 'press_release',
                        'description' => 'Envío de comunicado técnico',
                        'successful' => true,
                        'timestamp' => Carbon::now()->subDays(14)->toISOString(),
                    ],
                ],
                'last_contacted_at' => Carbon::now()->subDays(14),
                'last_response_at' => Carbon::now()->subDays(13),
                'verified_at' => Carbon::now()->subMonths(8),
            ],
        ];

        foreach ($contacts as $contact) {
            MediaContact::create($contact);
        }

        $this->command->info('Se han creado ' . count($contacts) . ' contactos de medios.');
    }
}

