<?php

namespace Database\Seeders;

use App\Models\NewsSource;
use Illuminate\Database\Seeder;

class NewsSourceSeeder extends Seeder
{
    public function run(): void
    {
        $sources = [
            [
                'name' => 'El País',
                'url' => 'https://elpais.com',
                'type' => 'newspaper',
                'reliability_score' => 9.50,
                'update_frequency' => 'hourly',
                'is_active' => true,
                'categories' => json_encode(['general', 'nacional', 'internacional', 'política', 'economía']),
                'geographic_scope' => 'national',
                'language' => 'es',
                'articles_per_day' => 150,
            ],
            [
                'name' => 'El Mundo',
                'url' => 'https://elmundo.es',
                'type' => 'newspaper',
                'reliability_score' => 9.00,
                'update_frequency' => 'hourly',
                'is_active' => true,
                'categories' => json_encode(['general', 'nacional', 'política', 'economía', 'deportes']),
                'geographic_scope' => 'national',
                'language' => 'es',
                'articles_per_day' => 120,
            ],
            [
                'name' => 'ABC',
                'url' => 'https://abc.es',
                'type' => 'newspaper',
                'reliability_score' => 8.80,
                'update_frequency' => 'hourly',
                'is_active' => true,
                'categories' => json_encode(['general', 'nacional', 'política', 'economía', 'cultura']),
                'geographic_scope' => 'national',
                'language' => 'es',
                'articles_per_day' => 100,
            ],
            [
                'name' => 'La Vanguardia',
                'url' => 'https://lavanguardia.com',
                'type' => 'newspaper',
                'reliability_score' => 9.20,
                'update_frequency' => 'hourly',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'internacional']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 80,
            ],
            [
                'name' => 'El Periódico',
                'url' => 'https://elperiodico.com',
                'type' => 'newspaper',
                'reliability_score' => 8.90,
                'update_frequency' => 'hourly',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'política']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 70,
            ],
            [
                'name' => 'El Correo',
                'url' => 'https://elcorreo.com',
                'type' => 'newspaper',
                'reliability_score' => 8.70,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 60,
            ],
            [
                'name' => 'El Diario Vasco',
                'url' => 'https://diariovasco.com',
                'type' => 'newspaper',
                'reliability_score' => 8.60,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 55,
            ],
            [
                'name' => 'El Norte de Castilla',
                'url' => 'https://elnortedecastilla.es',
                'type' => 'newspaper',
                'reliability_score' => 8.50,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 50,
            ],
            [
                'name' => 'El Día',
                'url' => 'https://eldia.es',
                'type' => 'newspaper',
                'reliability_score' => 8.40,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 45,
            ],
            [
                'name' => 'La Nueva España',
                'url' => 'https://lne.es',
                'type' => 'newspaper',
                'reliability_score' => 8.30,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 40,
            ],
            [
                'name' => 'El Faro de Vigo',
                'url' => 'https://farodevigo.es',
                'type' => 'newspaper',
                'reliability_score' => 8.20,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 35,
            ],
            [
                'name' => 'El Ideal',
                'url' => 'https://ideal.es',
                'type' => 'newspaper',
                'reliability_score' => 8.10,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 30,
            ],
            [
                'name' => 'El Comercio',
                'url' => 'https://elcomercio.es',
                'type' => 'newspaper',
                'reliability_score' => 8.00,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 25,
            ],
            [
                'name' => 'El Diario Montañés',
                'url' => 'https://eldiariomontanes.es',
                'type' => 'newspaper',
                'reliability_score' => 7.90,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 20,
            ],
            [
                'name' => 'El Heraldo de Aragón',
                'url' => 'https://heraldo.es',
                'type' => 'newspaper',
                'reliability_score' => 7.80,
                'update_frequency' => 'daily',
                'is_active' => true,
                'categories' => json_encode(['general', 'regional', 'nacional', 'local']),
                'geographic_scope' => 'regional',
                'language' => 'es',
                'articles_per_day' => 15,
            ]
        ];

        foreach ($sources as $source) {
            NewsSource::create($source);
        }
    }
}
