<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductionRight;
use App\Models\User;
use App\Models\EnergyInstallation;
use App\Models\ProjectProposal;
use Carbon\Carbon;

class ProductionRightsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener usuarios existentes
        $users = User::all();
        
        if ($users->isEmpty()) {
            $this->command->warn('No hay usuarios disponibles. Ejecuta UsersSeeder primero.');
            return;
        }

        // Obtener instalaciones existentes
        $installations = EnergyInstallation::all();
        
        // Obtener propuestas de proyecto existentes
        $projectProposals = ProjectProposal::all();

        $rights = [
            // Derechos de producción solar residencial
            [
                'seller_id' => $users->random()->id,
                'buyer_id' => null,
                'installation_id' => $installations->isNotEmpty() ? $installations->random()->id : null,
                'project_proposal_id' => $projectProposals->isNotEmpty() ? $projectProposals->random()->id : null,
                'title' => 'Derechos de Producción Solar Residencial - Madrid',
                'slug' => 'derechos-produccion-solar-residencial-madrid',
                'description' => 'Venta de derechos de producción de instalación solar fotovoltaica residencial de 5kW en Madrid.',
                'right_identifier' => 'PR-2024-' . strtoupper(uniqid()),
                'right_type' => 'energy_production',
                'total_capacity_kw' => 5.0,
                'available_capacity_kw' => 5.0,
                'reserved_capacity_kw' => 0.0,
                'sold_capacity_kw' => 0.0,
                'estimated_annual_production_kwh' => 7500.0,
                'guaranteed_annual_production_kwh' => 7000.0,
                'actual_annual_production_kwh' => 0.0,
                'valid_from' => Carbon::now()->addDays(30),
                'valid_until' => Carbon::now()->addYears(20),
                'duration_years' => 20,
                'renewable_right' => true,
                'renewal_period_years' => 5,
                'pricing_model' => 'fixed_price_kwh',
                'price_per_kwh' => 0.12,
                'market_premium_percentage' => 0.0,
                'minimum_guaranteed_price' => 0.10,
                'maximum_price_cap' => 0.15,
                'price_escalation_terms' => null,
                'upfront_payment' => 0.0,
                'periodic_payment' => 0.0,
                'payment_frequency' => 'monthly',
                'security_deposit' => 500.0,
                'payment_terms' => null,
                'penalty_clauses' => null,
                'production_guaranteed' => true,
                'production_guarantee_percentage' => 95.0,
                'insurance_included' => true,
                'insurance_details' => null,
                'risk_allocation' => null,
                'buyer_rights' => null,
                'buyer_obligations' => null,
                'seller_rights' => null,
                'seller_obligations' => null,
                'is_transferable' => true,
                'max_transfers' => 3,
                'current_transfers' => 0,
                'transfer_restrictions' => null,
                'transfer_fee_percentage' => 2.0,
                'status' => 'available',
                'status_notes' => 'Derecho disponible para venta inmediata',
                'contract_signed_at' => null,
                'activated_at' => null,
                'current_month_production_kwh' => 0.0,
                'ytd_production_kwh' => 0.0,
                'lifetime_production_kwh' => 0.0,
                'performance_ratio' => 0.0,
                'monthly_production_history' => [],
                'regulatory_framework' => 'RD 244/2019',
                'applicable_regulations' => null,
                'grid_code_compliant' => true,
                'certifications' => null,
                'legal_documents' => null,
                'contract_template_version' => '2.1',
                'electronic_signature_valid' => true,
                'signature_details' => null,
                'views_count' => rand(50, 500),
                'inquiries_count' => rand(5, 25),
                'offers_received' => rand(0, 10),
                'highest_offer_price' => 0.13,
                'average_market_price' => 0.125,
                'is_active' => true,
                'is_featured' => true,
                'auto_accept_offers' => false,
                'auto_accept_threshold' => 0.0,
                'allow_partial_sales' => true,
                'minimum_sale_capacity_kw' => 1.0,
            ],

            // Derechos de producción solar comercial
            [
                'seller_id' => $users->random()->id,
                'buyer_id' => null,
                'installation_id' => $installations->isNotEmpty() ? $installations->random()->id : null,
                'project_proposal_id' => $projectProposals->isNotEmpty() ? $projectProposals->random()->id : null,
                'title' => 'Derechos de Producción Solar Comercial - Barcelona',
                'slug' => 'derechos-produccion-solar-comercial-barcelona',
                'description' => 'Venta de derechos de producción de instalación solar fotovoltaica comercial de 50kW en Barcelona.',
                'right_identifier' => 'PR-2024-' . strtoupper(uniqid()),
                'right_type' => 'energy_production',
                'total_capacity_kw' => 50.0,
                'available_capacity_kw' => 50.0,
                'reserved_capacity_kw' => 0.0,
                'sold_capacity_kw' => 0.0,
                'estimated_annual_production_kwh' => 75000.0,
                'guaranteed_annual_production_kwh' => 70000.0,
                'actual_annual_production_kwh' => 0.0,
                'valid_from' => Carbon::now()->addDays(60),
                'valid_until' => Carbon::now()->addYears(25),
                'duration_years' => 25,
                'renewable_right' => true,
                'renewal_period_years' => 5,
                'pricing_model' => 'market_price',
                'price_per_kwh' => 0.0,
                'market_premium_percentage' => 5.0,
                'minimum_guaranteed_price' => 0.08,
                'maximum_price_cap' => 0.20,
                'price_escalation_terms' => null,
                'upfront_payment' => 5000.0,
                'periodic_payment' => 0.0,
                'payment_frequency' => 'monthly',
                'security_deposit' => 10000.0,
                'payment_terms' => null,
                'penalty_clauses' => null,
                'production_guaranteed' => true,
                'production_guarantee_percentage' => 90.0,
                'insurance_included' => true,
                'insurance_details' => null,
                'risk_allocation' => null,
                'buyer_rights' => null,
                'buyer_obligations' => null,
                'seller_rights' => null,
                'seller_obligations' => null,
                'is_transferable' => true,
                'max_transfers' => 5,
                'current_transfers' => 0,
                'transfer_restrictions' => null,
                'transfer_fee_percentage' => 1.5,
                'status' => 'available',
                'status_notes' => 'Derecho disponible para venta inmediata',
                'contract_signed_at' => null,
                'activated_at' => null,
                'current_month_production_kwh' => 0.0,
                'ytd_production_kwh' => 0.0,
                'lifetime_production_kwh' => 0.0,
                'performance_ratio' => 0.0,
                'monthly_production_history' => [],
                'regulatory_framework' => 'RD 244/2019',
                'applicable_regulations' => null,
                'grid_code_compliant' => true,
                'certifications' => null,
                'legal_documents' => null,
                'contract_template_version' => '3.0',
                'electronic_signature_valid' => true,
                'signature_details' => null,
                'views_count' => rand(100, 1000),
                'inquiries_count' => rand(10, 50),
                'offers_received' => rand(2, 20),
                'highest_offer_price' => 0.15,
                'average_market_price' => 0.12,
                'is_active' => true,
                'is_featured' => true,
                'auto_accept_offers' => false,
                'auto_accept_threshold' => 0.0,
                'allow_partial_sales' => true,
                'minimum_sale_capacity_kw' => 5.0,
            ],

            // Derechos de producción eólica
            [
                'seller_id' => $users->random()->id,
                'buyer_id' => null,
                'installation_id' => $installations->isNotEmpty() ? $installations->random()->id : null,
                'project_proposal_id' => $projectProposals->isNotEmpty() ? $projectProposals->random()->id : null,
                'title' => 'Derechos de Producción Eólica - Galicia',
                'slug' => 'derechos-produccion-eolica-galicia',
                'description' => 'Venta de derechos de producción de parque eólico de 2MW en Galicia.',
                'right_identifier' => 'PR-2024-' . strtoupper(uniqid()),
                'right_type' => 'energy_production',
                'total_capacity_kw' => 2000.0,
                'available_capacity_kw' => 2000.0,
                'reserved_capacity_kw' => 0.0,
                'sold_capacity_kw' => 0.0,
                'estimated_annual_production_kwh' => 6000000.0,
                'guaranteed_annual_production_kwh' => 5400000.0,
                'actual_annual_production_kwh' => 0.0,
                'valid_from' => Carbon::now()->addDays(90),
                'valid_until' => Carbon::now()->addYears(30),
                'duration_years' => 30,
                'renewable_right' => true,
                'renewal_period_years' => 10,
                'pricing_model' => 'premium_over_market',
                'price_per_kwh' => 0.0,
                'market_premium_percentage' => 10.0,
                'minimum_guaranteed_price' => 0.06,
                'maximum_price_cap' => 0.25,
                'price_escalation_terms' => null,
                'upfront_payment' => 50000.0,
                'periodic_payment' => 0.0,
                'payment_frequency' => 'monthly',
                'security_deposit' => 100000.0,
                'payment_terms' => null,
                'penalty_clauses' => null,
                'production_guaranteed' => true,
                'production_guarantee_percentage' => 85.0,
                'insurance_included' => true,
                'insurance_details' => null,
                'risk_allocation' => null,
                'buyer_rights' => null,
                'buyer_obligations' => null,
                'seller_rights' => null,
                'seller_obligations' => null,
                'is_transferable' => true,
                'max_transfers' => 10,
                'current_transfers' => 0,
                'transfer_restrictions' => null,
                'transfer_fee_percentage' => 1.0,
                'status' => 'available',
                'status_notes' => 'Derecho disponible para venta inmediata',
                'contract_signed_at' => null,
                'activated_at' => null,
                'current_month_production_kwh' => 0.0,
                'ytd_production_kwh' => 0.0,
                'lifetime_production_kwh' => 0.0,
                'performance_ratio' => 0.0,
                'monthly_production_history' => [],
                'regulatory_framework' => 'RD 244/2019',
                'applicable_regulations' => null,
                'grid_code_compliant' => true,
                'certifications' => null,
                'legal_documents' => null,
                'contract_template_version' => '2.5',
                'electronic_signature_valid' => true,
                'signature_details' => null,
                'views_count' => rand(200, 2000),
                'inquiries_count' => rand(20, 100),
                'offers_received' => rand(5, 30),
                'highest_offer_price' => 0.18,
                'average_market_price' => 0.15,
                'is_active' => true,
                'is_featured' => true,
                'auto_accept_offers' => false,
                'auto_accept_threshold' => 0.0,
                'allow_partial_sales' => true,
                'minimum_sale_capacity_kw' => 100.0,
            ],
        ];

        foreach ($rights as $right) {
            ProductionRight::create($right);
        }

        $this->command->info('Se han creado ' . count($rights) . ' derechos de producción.');
    }
}