<?php

namespace Database\Seeders;

use App\Models\Quote;
use Illuminate\Database\Seeder;

class QuoteSeeder extends Seeder
{
    public function run(): void
    {
        $quotes = [
            [
                'text' => 'El conocimiento es poder',
                'author' => 'Francis Bacon',
                'source' => 'Meditationes Sacrae',
                'language' => 'la',
                'category' => 'Filosofía',
                'tags' => json_encode(['conocimiento', 'poder', 'filosofía', 'ciencia']),
                'mood' => 'inspirational',
                'difficulty_level' => 'medium',
                'word_count' => 4,
                'character_count' => 22,
                'popularity_score' => 9.5,
                'usage_count' => 15000,
                'translations' => json_encode(['en' => 'Knowledge is power', 'fr' => 'La connaissance est le pouvoir']),
                'is_verified' => true,
            ],
            [
                'text' => 'Ser o no ser, esa es la cuestión',
                'author' => 'William Shakespeare',
                'source' => 'Hamlet',
                'language' => 'en',
                'category' => 'Literatura',
                'tags' => json_encode(['Shakespeare', 'Hamlet', 'teatro', 'existencia', 'drama']),
                'mood' => 'philosophical',
                'difficulty_level' => 'hard',
                'word_count' => 9,
                'character_count' => 42,
                'popularity_score' => 9.8,
                'usage_count' => 25000,
                'translations' => json_encode(['es' => 'Ser o no ser, esa es la cuestión', 'fr' => 'Être ou ne pas être, telle est la question']),
                'is_verified' => true,
            ],
            [
                'text' => 'La vida es lo que pasa mientras estás ocupado haciendo otros planes',
                'author' => 'John Lennon',
                'source' => 'Beautiful Boy (Darling Boy)',
                'language' => 'en',
                'category' => 'Vida',
                'tags' => json_encode(['Lennon', 'vida', 'música', 'Beatles', 'reflexión']),
                'mood' => 'reflective',
                'difficulty_level' => 'medium',
                'word_count' => 15,
                'character_count' => 89,
                'popularity_score' => 9.2,
                'usage_count' => 18000,
                'translations' => json_encode(['es' => 'La vida es lo que pasa mientras estás ocupado haciendo otros planes']),
                'is_verified' => true,
            ],
            [
                'text' => 'La imaginación es más importante que el conocimiento',
                'author' => 'Albert Einstein',
                'source' => 'Entrevista con The Saturday Evening Post',
                'language' => 'de',
                'category' => 'Ciencia',
                'tags' => json_encode(['Einstein', 'imaginación', 'conocimiento', 'ciencia', 'física']),
                'mood' => 'inspirational',
                'difficulty_level' => 'medium',
                'word_count' => 9,
                'character_count' => 58,
                'popularity_score' => 9.4,
                'usage_count' => 20000,
                'translations' => json_encode(['en' => 'Imagination is more important than knowledge', 'es' => 'La imaginación es más importante que el conocimiento']),
                'is_verified' => true,
            ],
            [
                'text' => 'El amor es paciente, el amor es bondadoso',
                'author' => 'San Pablo',
                'source' => 'Primera Carta a los Corintios',
                'language' => 'gr',
                'category' => 'Amor',
                'tags' => json_encode(['amor', 'Biblia', 'San Pablo', 'religión', 'bondad']),
                'mood' => 'loving',
                'difficulty_level' => 'easy',
                'word_count' => 8,
                'character_count' => 42,
                'popularity_score' => 9.6,
                'usage_count' => 12000,
                'translations' => json_encode(['en' => 'Love is patient, love is kind', 'es' => 'El amor es paciente, el amor es bondadoso']),
                'is_verified' => true,
            ],
            [
                'text' => 'La educación es el arma más poderosa que puedes usar para cambiar el mundo',
                'author' => 'Nelson Mandela',
                'source' => 'Discurso en la Universidad de Witwatersrand',
                'language' => 'en',
                'category' => 'Educación',
                'tags' => json_encode(['Mandela', 'educación', 'cambio', 'Sudáfrica', 'libertad']),
                'mood' => 'inspirational',
                'difficulty_level' => 'medium',
                'word_count' => 18,
                'character_count' => 108,
                'popularity_score' => 9.3,
                'usage_count' => 16000,
                'translations' => json_encode(['es' => 'La educación es el arma más poderosa que puedes usar para cambiar el mundo']),
                'is_verified' => true,
            ],
            [
                'text' => 'La creatividad es la inteligencia divirtiéndose',
                'author' => 'Albert Einstein',
                'source' => 'Cita atribuida',
                'language' => 'en',
                'category' => 'Creatividad',
                'tags' => json_encode(['Einstein', 'creatividad', 'inteligencia', 'diversión', 'genio']),
                'mood' => 'playful',
                'difficulty_level' => 'easy',
                'word_count' => 8,
                'character_count' => 52,
                'popularity_score' => 8.8,
                'usage_count' => 8000,
                'translations' => json_encode(['es' => 'La creatividad es la inteligencia divirtiéndose']),
                'is_verified' => false,
            ],
            [
                'text' => 'El éxito no es la clave de la felicidad. La felicidad es la clave del éxito',
                'author' => 'Albert Schweitzer',
                'source' => 'Cita atribuida',
                'language' => 'en',
                'category' => 'Éxito',
                'tags' => json_encode(['Schweitzer', 'éxito', 'felicidad', 'filosofía', 'vida']),
                'mood' => 'motivational',
                'difficulty_level' => 'medium',
                'word_count' => 16,
                'character_count' => 95,
                'popularity_score' => 9.0,
                'usage_count' => 10000,
                'translations' => json_encode(['es' => 'El éxito no es la clave de la felicidad. La felicidad es la clave del éxito']),
                'is_verified' => false,
            ],
            [
                'text' => 'La sabiduría comienza en el asombro',
                'author' => 'Sócrates',
                'source' => 'Diálogos de Platón',
                'language' => 'gr',
                'category' => 'Sabiduría',
                'tags' => json_encode(['Sócrates', 'sabiduría', 'asombro', 'filosofía', 'Grecia']),
                'mood' => 'philosophical',
                'difficulty_level' => 'medium',
                'word_count' => 7,
                'character_count' => 38,
                'popularity_score' => 9.1,
                'usage_count' => 9000,
                'translations' => json_encode(['en' => 'Wisdom begins in wonder', 'es' => 'La sabiduría comienza en el asombro']),
                'is_verified' => true,
            ],
            [
                'text' => 'No hay viento favorable para el que no sabe a dónde va',
                'author' => 'Séneca',
                'source' => 'Cartas a Lucilio',
                'language' => 'la',
                'category' => 'Motivación',
                'tags' => json_encode(['Séneca', 'objetivos', 'dirección', 'filosofía', 'Roma']),
                'mood' => 'motivational',
                'difficulty_level' => 'medium',
                'word_count' => 12,
                'character_count' => 58,
                'popularity_score' => 8.9,
                'usage_count' => 7000,
                'translations' => json_encode(['en' => 'There is no favorable wind for the one who doesn\'t know where to go', 'es' => 'No hay viento favorable para el que no sabe a dónde va']),
                'is_verified' => true,
            ],
            [
                'text' => 'La belleza está en los ojos del que mira',
                'author' => 'Margaret Wolfe Hungerford',
                'source' => 'Molly Bawn',
                'language' => 'en',
                'category' => 'Vida',
                'tags' => json_encode(['belleza', 'percepción', 'literatura', 'subjetividad', 'amor']),
                'mood' => 'romantic',
                'difficulty_level' => 'easy',
                'word_count' => 10,
                'character_count' => 48,
                'popularity_score' => 9.2,
                'usage_count' => 14000,
                'translations' => json_encode(['es' => 'La belleza está en los ojos del que mira']),
                'is_verified' => true,
            ],
            [
                'text' => 'La ciencia no es solo compatible con la espiritualidad; es una fuente profunda de espiritualidad',
                'author' => 'Carl Sagan',
                'source' => 'El mundo y sus demonios',
                'language' => 'en',
                'category' => 'Ciencia',
                'tags' => json_encode(['Sagan', 'ciencia', 'espiritualidad', 'cosmos', 'astronomía']),
                'mood' => 'philosophical',
                'difficulty_level' => 'hard',
                'word_count' => 18,
                'character_count' => 115,
                'popularity_score' => 8.7,
                'usage_count' => 6000,
                'translations' => json_encode(['es' => 'La ciencia no es solo compatible con la espiritualidad; es una fuente profunda de espiritualidad']),
                'is_verified' => true,
            ],
            [
                'text' => 'El tiempo es el mejor maestro. Lamentablemente, mata a todos sus estudiantes',
                'author' => 'Hector Berlioz',
                'source' => 'Cita atribuida',
                'language' => 'fr',
                'category' => 'Vida',
                'tags' => json_encode(['Berlioz', 'tiempo', 'muerte', 'música', 'filosofía']),
                'mood' => 'melancholic',
                'difficulty_level' => 'medium',
                'word_count' => 14,
                'character_count' => 82,
                'popularity_score' => 8.5,
                'usage_count' => 5000,
                'translations' => json_encode(['en' => 'Time is the best teacher. Unfortunately, it kills all its students', 'es' => 'El tiempo es el mejor maestro. Lamentablemente, mata a todos sus estudiantes']),
                'is_verified' => false,
            ],
            [
                'text' => 'La música es el lenguaje universal de la humanidad',
                'author' => 'Henry Wadsworth Longfellow',
                'source' => 'Outre-Mer: A Pilgrimage Beyond the Sea',
                'language' => 'en',
                'category' => 'Literatura',
                'tags' => json_encode(['Longfellow', 'música', 'lenguaje', 'universal', 'humanidad']),
                'mood' => 'inspirational',
                'difficulty_level' => 'medium',
                'word_count' => 10,
                'character_count' => 58,
                'popularity_score' => 8.8,
                'usage_count' => 8000,
                'translations' => json_encode(['es' => 'La música es el lenguaje universal de la humanidad']),
                'is_verified' => true,
            ],
            [
                'text' => 'La verdad es más extraña que la ficción',
                'author' => 'Mark Twain',
                'source' => 'Following the Equator',
                'language' => 'en',
                'category' => 'Literatura',
                'tags' => json_encode(['Twain', 'verdad', 'ficción', 'realidad', 'literatura']),
                'mood' => 'philosophical',
                'difficulty_level' => 'easy',
                'word_count' => 8,
                'character_count' => 42,
                'popularity_score' => 9.1,
                'usage_count' => 11000,
                'translations' => json_encode(['es' => 'La verdad es más extraña que la ficción']),
                'is_verified' => true,
            ]
        ];

        foreach ($quotes as $quote) {
            Quote::create($quote);
        }
    }
}
