<?php

namespace Database\Seeders;

use App\Models\RealTimePrice;
use Illuminate\Database\Seeder;

class RealTimePriceSeeder extends Seeder
{
    public function run(): void
    {
        $prices = [
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 85.50,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(1),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'canarias',
                'price' => 120.75,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(1),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'baleares',
                'price' => 95.25,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(1),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 45.80,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(1),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'canarias',
                'price' => 65.40,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(1),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'oil',
                'zone' => 'global',
                'price' => 78.50,
                'currency' => 'USD',
                'unit' => 'barrel',
                'timestamp' => now()->subHours(2),
                'source' => 'ICE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'futures', 'verified' => true]),
            ],
            [
                'energy_type' => 'coal',
                'zone' => 'global',
                'price' => 95.25,
                'currency' => 'USD',
                'unit' => 'ton',
                'timestamp' => now()->subHours(3),
                'source' => 'ICE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'futures', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 92.30,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(2),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 78.90,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(3),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 105.60,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(4),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 48.20,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(2),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 42.15,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(3),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'oil',
                'zone' => 'global',
                'price' => 79.80,
                'currency' => 'USD',
                'unit' => 'barrel',
                'timestamp' => now()->subHours(4),
                'source' => 'ICE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'futures', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 88.45,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(5),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 76.20,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(6),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 44.80,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(4),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 47.30,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(5),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'oil',
                'zone' => 'global',
                'price' => 77.90,
                'currency' => 'USD',
                'unit' => 'barrel',
                'timestamp' => now()->subHours(6),
                'source' => 'ICE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'futures', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 82.15,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(7),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'electricity',
                'zone' => 'peninsula',
                'price' => 89.70,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(8),
                'source' => 'OMIE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 46.50,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(6),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'gas',
                'zone' => 'peninsula',
                'price' => 43.90,
                'currency' => 'EUR',
                'unit' => 'MWh',
                'timestamp' => now()->subHours(7),
                'source' => 'MIBGAS',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'spot', 'verified' => true]),
            ],
            [
                'energy_type' => 'oil',
                'zone' => 'global',
                'price' => 76.40,
                'currency' => 'USD',
                'unit' => 'barrel',
                'timestamp' => now()->subHours(8),
                'source' => 'ICE',
                'data_quality' => 'high',
                'additional_data' => json_encode(['market' => 'futures', 'verified' => true]),
            ]
        ];

        foreach ($prices as $price) {
            RealTimePrice::create($price);
        }
    }
}
