<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\V1\AppSettingController;
use App\Http\Controllers\Api\V1\ProvinceController;
use App\Http\Controllers\Api\V1\CountryController;
use App\Http\Controllers\Api\V1\LanguageController;
use App\Http\Controllers\Api\V1\TimezoneController;
use App\Http\Controllers\Api\V1\MunicipalityController;
use App\Http\Controllers\Api\V1\PointOfInterestController;
use App\Http\Controllers\Api\V1\AutonomousCommunityController;
use App\Http\Controllers\Api\V1\PersonController;
use App\Http\Controllers\Api\V1\ImageController;
use App\Http\Controllers\Api\V1\ProfessionController;
use App\Http\Controllers\Api\V1\WorkController;
use App\Http\Controllers\Api\V1\LinkController;
use App\Http\Controllers\Api\V1\AwardController;
use App\Http\Controllers\Api\V1\AwardWinnerController;
use App\Http\Controllers\Api\V1\FamilyMemberController;

Route::prefix('v1')->middleware('auth:sanctum')->group(function () {
    Route::apiResource('app-settings', AppSettingController::class)->only(['index', 'show']);
    Route::post('/points-of-interest', [PointOfInterestController::class, 'store']);
    Route::put('/points-of-interest/{id}', [PointOfInterestController::class, 'update']);
    // Route::delete('/points-of-interest/{id}', [PointOfInterestController::class, 'destroy']);
    Route::post('/images', [ImageController::class, 'store']);
    Route::put('/images/{id}', [ImageController::class, 'update']);
    Route::delete('/images/{id}', [ImageController::class, 'destroy']);
    Route::post('/professions', [ProfessionController::class, 'store']);
    Route::post('/works', [WorkController::class, 'store']);
    Route::post('/links', [LinkController::class, 'store']);
    Route::post('/awards', [AwardController::class, 'store']);
    Route::post('/award-winners', [AwardWinnerController::class, 'store']);
});

// Rutas públicas sin autenticación
Route::prefix('v1')->group(function () {
    Route::get('/provinces', [ProvinceController::class, 'index']);
    Route::get('/provinces/with-municipalities-count', [ProvinceController::class, 'withMunicipalitiesCount']);
    Route::get('/provinces/filter/by-area', [ProvinceController::class, 'filterByArea']);
    Route::get('/provinces/search', [ProvinceController::class, 'search']);
    Route::get('/provinces/largest/{limit}', [ProvinceController::class, 'largest']);
    Route::get('/provinces/by-autonomous-community/{slug}', [ProvinceController::class, 'byAutonomousCommunity']);
    Route::get('/provinces/{idOrSlug}', [ProvinceController::class, 'show']);
    Route::get('/countries', [CountryController::class, 'index']);
    Route::get('/countries/{idOrSlug}', [CountryController::class, 'show']);
    Route::get('/languages', [LanguageController::class, 'index']);
    Route::get('/languages/{idOrSlug}', [LanguageController::class, 'show']);
    Route::get('/timezones', [TimezoneController::class, 'index']);
    Route::get('/timezones/{idOrName}', [TimezoneController::class, 'show']);
    Route::get('/municipalities', [MunicipalityController::class, 'index']);
    Route::get('/municipalities/filter/by-population', [MunicipalityController::class, 'filterByPopulation']);
    Route::get('/municipalities/filter/by-area', [MunicipalityController::class, 'filterByArea']);
    Route::get('/municipalities/search', [MunicipalityController::class, 'search']);
    Route::get('/municipalities/largest/{limit}', [MunicipalityController::class, 'largest']);
    Route::get('/municipalities/province/{slug}', [MunicipalityController::class, 'byProvince']);
    Route::get('/municipalities/country/{slug}', [MunicipalityController::class, 'byCountry']);
    Route::get('/municipalities/{idOrSlug}', [MunicipalityController::class, 'show']);
    Route::get('/points-of-interest', [PointOfInterestController::class, 'index']);
    Route::get('/points-of-interest/{idOrSlug}', [PointOfInterestController::class, 'show']);
    Route::get('/points-of-interest/municipality/{slug}', [PointOfInterestController::class, 'byMunicipality']);
    Route::get('/points-of-interest/type/{type}', [PointOfInterestController::class, 'byType']);
    Route::get('/points-of-interest/tag/{tagSlug}', [PointOfInterestController::class, 'byTag']);
    Route::get('/autonomous-communities', [AutonomousCommunityController::class, 'index']);
    Route::get('/autonomous-communities/{slug}', [AutonomousCommunityController::class, 'show']);
    Route::get('/autonomous-communities-with-provinces', [AutonomousCommunityController::class, 'withProvinces']);
    Route::get('/autonomous-communities-with-provinces-and-municipalities', [AutonomousCommunityController::class, 'withProvincesAndMunicipalities']);
    Route::get('/persons', [PersonController::class, 'index']);
    Route::get('/persons/{idOrSlug}', [PersonController::class, 'show']);
    Route::get('/images', [ImageController::class, 'index']);
    Route::get('/images/{id}', [ImageController::class, 'show']);
    Route::get('/professions', [ProfessionController::class, 'index']);
    Route::get('/professions/{idOrSlug}', [ProfessionController::class, 'show']);
    Route::get('/works', [WorkController::class, 'index']);
    Route::get('/works/{idOrSlug}', [WorkController::class, 'show']);
    Route::get('/links', [LinkController::class, 'index']);
    Route::get('/links/{id}', [LinkController::class, 'show']);
    Route::get('/awards', [AwardController::class, 'index']);
    Route::get('/awards/{idOrSlug}', [AwardController::class, 'show']);
    Route::get('/award-winners', [AwardWinnerController::class, 'index']);
    Route::get('/award-winners/{id}', [AwardWinnerController::class, 'show']);
    Route::get('/family-members', [FamilyMemberController::class, 'index']);
    Route::get('/family-members/{id}', [FamilyMemberController::class, 'show']);
    Route::get('/regions', [\App\Http\Controllers\Api\V1\RegionController::class, 'index']);
    Route::get('/regions/{idOrSlug}', [\App\Http\Controllers\Api\V1\RegionController::class, 'show']);
    Route::get('/provinces/{slug}/regions', [\App\Http\Controllers\Api\V1\RegionController::class, 'byProvince']);
    Route::get('/autonomous-communities/{slug}/regions', [\App\Http\Controllers\Api\V1\RegionController::class, 'byAutonomousCommunity']);
    Route::get('/countries/{slug}/regions', [\App\Http\Controllers\Api\V1\RegionController::class, 'byCountry']);
    Route::get('/anniversaries', [\App\Http\Controllers\Api\V1\AnniversaryController::class, 'index']);
    Route::get('/anniversaries/{idOrSlug}', [\App\Http\Controllers\Api\V1\AnniversaryController::class, 'show']);
    Route::get('/anniversaries/day/{month}/{day}', [\App\Http\Controllers\Api\V1\AnniversaryController::class, 'byDay']);
    Route::get('/calendar-holidays', [\App\Http\Controllers\Api\V1\CalendarHolidayController::class, 'index']);
    Route::get('/calendar-holidays/{idOrSlug}', [\App\Http\Controllers\Api\V1\CalendarHolidayController::class, 'show']);
    Route::get('/calendar-holidays/date/{date}', [\App\Http\Controllers\Api\V1\CalendarHolidayController::class, 'byDate']);
    Route::get('/events', [\App\Http\Controllers\Api\V1\EventController::class, 'index']);
    Route::get('/events/filter/by-date-range', [\App\Http\Controllers\Api\V1\EventController::class, 'filterByDateRange']);
    Route::get('/events/filter/by-location', [\App\Http\Controllers\Api\V1\EventController::class, 'filterByLocation']);
    Route::get('/events/filter/by-type', [\App\Http\Controllers\Api\V1\EventController::class, 'filterByType']);
    Route::get('/events/search', [\App\Http\Controllers\Api\V1\EventController::class, 'search']);
    Route::get('/events/upcoming/{days}', [\App\Http\Controllers\Api\V1\EventController::class, 'upcoming']);
    Route::get('/events/{idOrSlug}', [\App\Http\Controllers\Api\V1\EventController::class, 'show']);
    Route::get('/event-types', [\App\Http\Controllers\Api\V1\EventTypeController::class, 'index']);
    Route::get('/event-types/{idOrSlug}', [\App\Http\Controllers\Api\V1\EventTypeController::class, 'show']);
    Route::get('/venues', [\App\Http\Controllers\Api\V1\VenueController::class, 'index']);
    Route::get('/venues/{idOrSlug}', [\App\Http\Controllers\Api\V1\VenueController::class, 'show']);
    Route::post('/venues', [\App\Http\Controllers\Api\V1\VenueController::class, 'store']);
    Route::get('/artists', [\App\Http\Controllers\Api\V1\ArtistController::class, 'index']);
    Route::get('/artists/{idOrSlug}', [\App\Http\Controllers\Api\V1\ArtistController::class, 'show']);
    Route::post('/artists', [\App\Http\Controllers\Api\V1\ArtistController::class, 'store']);
    Route::get('/groups', [\App\Http\Controllers\Api\V1\GroupController::class, 'index']);
    Route::get('/groups/{id}', [\App\Http\Controllers\Api\V1\GroupController::class, 'show']);
    Route::post('/groups', [\App\Http\Controllers\Api\V1\GroupController::class, 'store']);
    Route::get('/festivals', [\App\Http\Controllers\Api\V1\FestivalController::class, 'index']);
    Route::get('/festivals/filter/by-location', [\App\Http\Controllers\Api\V1\FestivalController::class, 'filterByLocation']);
    Route::get('/festivals/search', [\App\Http\Controllers\Api\V1\FestivalController::class, 'search']);
    Route::post('/festivals', [\App\Http\Controllers\Api\V1\FestivalController::class, 'store']);
    // Specific festival routes must come before {id} routes
    Route::get('/festivals/today', [\App\Http\Controllers\Api\V1\FestivalController::class, 'today']);
    Route::get('/festivals/this-week', [\App\Http\Controllers\Api\V1\FestivalController::class, 'thisWeek']);
    Route::get('/festivals/this-month', [\App\Http\Controllers\Api\V1\FestivalController::class, 'thisMonth']);
    Route::get('/festivals/this-year', [\App\Http\Controllers\Api\V1\FestivalController::class, 'thisYear']);
    Route::get('/festivals/municipality/{idOrSlug}', [\App\Http\Controllers\Api\V1\FestivalController::class, 'byMunicipality']);
    Route::get('/festivals/region/{idOrSlug}', [\App\Http\Controllers\Api\V1\FestivalController::class, 'byRegion']);
    Route::get('/festivals/province/{idOrSlug}', [\App\Http\Controllers\Api\V1\FestivalController::class, 'byProvince']);
    Route::get('/festivals/autonomous-community/{idOrSlug}', [\App\Http\Controllers\Api\V1\FestivalController::class, 'byAutonomousCommunity']);
    // Generic {id} routes come last
    Route::get('/festivals/{id}', [\App\Http\Controllers\Api\V1\FestivalController::class, 'show']);
    Route::get('/festivals/{id}/events', [\App\Http\Controllers\Api\V1\FestivalController::class, 'events']);
    Route::get('/festivals/{id}/artists', [\App\Http\Controllers\Api\V1\FestivalController::class, 'artists']);
    Route::get('/festivals-and-unassigned-events', [\App\Http\Controllers\Api\V1\FestivalController::class, 'festivalsAndUnassignedEvents']);
    Route::get('/festivals-with-events-and-unassigned', [\App\Http\Controllers\Api\V1\FestivalController::class, 'festivalsWithEventsAndUnassigned']);
});

Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});
